version: "3"

services:
  breakroom:
    container_name: breakroom
    image: breakroom # This is the name of the image we built in the previous step
    ports:
      - "3230:3230"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always  # This ensures the container auto-starts and restarts on failure
