version: "3"

services:
  breakroom:
    container_name: breakroom
    build:
      context: .
      dockerfile: Dockerfile
    image: breakroom
    ports:
      - "3230:3230"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always  # This ensures the container auto-starts and restarts on failure
