export default {
  activeIndex: 0,
  createFormLoading: false,
  images: [],
  imageListLoading: true,
  isShowingSideSheet: false,
  loading: false,
  logData: {},
  newGroupName: '',
  pageError: false,
  selectedImage: {},
  showImagePage: false,
  showNewImageForm: false, 
  showModal: false,
}